language: scala

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/
    - $HOME/.sbt/launchers

jdk:
  - oraclejdk8

matrix:
  include:
    - scala: 2.11.12
      env: SPARK_VERSION=2.2.1
    - scala: 2.10.7
      env: SPARK_VERSION=1.6.3

script:
  - sbt -Dfile.encoding=UTF8 -J-XX:ReservedCodeCacheSize=256M ";set g8Properties in g8 in Test ~= { _ + (\"scala_version\" -> \"$TRAVIS_SCALA_VERSION\") + (\"spark_version\" -> \"$SPARK_VERSION\")}; test"

  # Tricks to avoid unnecessary cache updates
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm
